name: Integration Service

on:
  push:
  pull_request:

jobs:
  continuos-integration:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
      
      - name: Instalando Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Instalando Rust e Cargo
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      
      - name: Instalando Yarn
        run: npm install -g yarn
      
      - name: Instalando dependências do javascriptcoregtk-4.0
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y libjavascriptcoregtk-4.0-dev
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            # Comando para instalação no macOS (se necessário)
            # Substitua pelo comando real, se necessário
            echo "Instalando dependências do javascriptcoregtk-4.0 no macOS"
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            # Comando para instalação no Windows (se necessário)
            # Substitua pelo comando real, se necessário
            echo "Instalando dependências do javascriptcoregtk-4.0 no Windows"
          fi
      
      - name: Instalando dependências do GDK-3.0
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y libgtk-3-dev
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            # Comando para instalação no macOS (se necessário)
            # Substitua pelo comando real, se necessário
            echo "Instalando dependências do GDK-3.0 no macOS"
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            # Comando para instalação no Windows (se necessário)
            # Substitua pelo comando real, se necessário
            echo "Instalando dependências do GDK-3.0 no Windows"
          fi
      
      - name: Configurando PKG_CONFIG_PATH
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            export PKG_CONFIG_PATH=/usr/lib/pkgconfig
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            # Comando para configuração no macOS (se necessário)
            # Substitua pelo comando real, se necessário
            echo "Configurando PKG_CONFIG_PATH no macOS"
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            # Comando para configuração no Windows (se necessário)
            # Substitua pelo comando real, se necessário
            echo "Configurando PKG_CONFIG_PATH no Windows"
          fi
      
      - name: Instalando dependências do libsoup-2.4
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y libsoup2.4-dev
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            # Comando para instalação no macOS (se necessário)
            # Substitua pelo comando real, se necessário
            echo "Instalando dependências do libsoup-2.4 no macOS"
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            # Comando para instalação no Windows (se necessário)
            # Substitua pelo comando real, se necessário
            echo "Instalando dependências do libsoup-2.4 no Windows"
          fi
      
      - name: Instalando dependências do projeto
        run: yarn install
      
      - name: Rodando build do Vite
        run: yarn run build
