name: Integration Service

on:
  push:
  pull_request:

jobs:
  continuos-integration:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v3
      - name: Instalando NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: 21.x
      - name: Instalando Rust e Cargo
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Instalando Yarn
        run: npm install -g yarn
      - name: Instalando dependências do GDK-3.0
        run: sudo apt-get install libgtk-3-dev -y
      - name: Configurando PKG_CONFIG_PATH
        run: export PKG_CONFIG_PATH=/usr/lib/pkgconfig
      - name: Instalando dependências do libsoup-2.4
        run: sudo apt-get install -y libsoup2.4-dev
      - name: Instalando dependências do projeto
        run: |
          yarn install
      - name: Rodando build do vite
        run: |
          yarn run build
      - name: Rodando build do tauri
        run: |
          yarn run tauri:build
