name: Integration Service

on: push

jobs:
  continuos-integration:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21.x
      - name: install yarn
        run: npm install -g yarn
      - name: yarn install, build and test
        run: |
          yarn install
          yarn run build
