name: Integration Service

on:
  push:
  pull_request:

jobs:
  continuos-integration:
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
      
      - name: Instalando Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21.x
      
      - name: Instalando Rust e Cargo
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      
      - name: Instalando Yarn
        run: npm install -g yarn
      - name: Instalando depedencias Yarn
        run: yarn install
      
      - name: Instalando dependências do javascriptcoregtk-4.0 (apenas para Ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get install -y 

      - name: Rodando build do VITE
        run: yarn run build
